### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by chezwhite** [Trey-Freeman/CS4310-node#4]
Do we need "emails" collection? We have "accounts" (I think should be renamed for "user") collection and we can save there the user's email.

**Comment by srjames90** [comment]
I think this is because the mailing list works under the assumption that not all registered users will be part of the mailing list, and that those in the mailing list aren't necessarily registered users. I'm not sure why anyone would want to join the mailing list without being registered or why registered users aren't automatically added to the mailing list, so I'm leaning towards agreeing with you; however, I'm not working in that feature, so I guess that's up to who's ever working on it. I think it's Trey.

**Comment by srjames90** [comment]
I meant to say "I'm not working on that feature, so I guess that's up to whoever is working on it." Sorry for the typo.

**Comment by Trey-Freeman** [comment]
Simi implemented it, but

Yes, I believe that the e-mail list is for non registered users who want to
receive e-mails.
